import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ReactNode } from "react";
import { BreadcrumbItem } from "@/types";
import { AuthProvider } from "@/contexts/auth-context";
import AppLayoutTemplate from "@/layouts/app/app-sidebar-layout";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

interface AppLayoutProps {
  children: ReactNode;
  breadcrumbs?: BreadcrumbItem[];
}

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children, breadcrumbs }: AppLayoutProps) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <AuthProvider>
          {/* <AppLayoutTemplate breadcrumbs={breadcrumbs}> */}
            {children}
          {/* </AppLayoutTemplate> */}
        </AuthProvider>
      </body>
    </html>
  );
}
